### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [3]:
!pip install tensorflow
#!pip install tensorflow-gpu

You should consider upgrading via the 'b:\prep\repository\nlp-with-ml\nlpvenv\scripts\python.exe -m pip install --upgrade pip' command.


In [4]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [5]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [11]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[209, 301, 315, 116], [209, 301, 315, 206], [209, 401, 315, 245], [18, 124, 75, 164, 178], [18, 124, 75, 164, 121], [250, 209, 123, 315, 263], [249, 136, 316, 164]]


### Word Embedding Represntation

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [16]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 209 301 315 116]
 [  0   0   0   0 209 301 315 206]
 [  0   0   0   0 209 401 315 245]
 [  0   0   0  18 124  75 164 178]
 [  0   0   0  18 124  75 164 121]
 [  0   0   0 250 209 123 315 263]
 [  0   0   0   0 249 136 316 164]]


In [18]:
## 10 feature dimesnions
dim=10


In [20]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse') # adam optimizer and mean square error 

In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 209, 301, 315, 116])

In [24]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 244ms/step


array([[-0.03420796, -0.03776937, -0.01532779,  0.02567506, -0.04505258,
        -0.04434186,  0.02496746, -0.03646117, -0.03092648,  0.02595485],
       [-0.03420796, -0.03776937, -0.01532779,  0.02567506, -0.04505258,
        -0.04434186,  0.02496746, -0.03646117, -0.03092648,  0.02595485],
       [-0.03420796, -0.03776937, -0.01532779,  0.02567506, -0.04505258,
        -0.04434186,  0.02496746, -0.03646117, -0.03092648,  0.02595485],
       [-0.03420796, -0.03776937, -0.01532779,  0.02567506, -0.04505258,
        -0.04434186,  0.02496746, -0.03646117, -0.03092648,  0.02595485],
       [-0.0162627 , -0.00686593,  0.0207576 , -0.03949002, -0.04378505,
         0.00830678,  0.04668463,  0.02091653,  0.03579111,  0.00138693],
       [ 0.04168551,  0.03062064,  0.01592472, -0.00214869, -0.04990872,
        -0.0081948 ,  0.04247181,  0.01584608,  0.02644379, -0.03842119],
       [-0.03838784, -0.02170075,  0.01314293, -0.03981489, -0.00875556,
        -0.03406781, -0.04632014, -0.03810064

In [25]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 66ms/step
[[[-0.03420796 -0.03776937 -0.01532779  0.02567506 -0.04505258
   -0.04434186  0.02496746 -0.03646117 -0.03092648  0.02595485]
  [-0.03420796 -0.03776937 -0.01532779  0.02567506 -0.04505258
   -0.04434186  0.02496746 -0.03646117 -0.03092648  0.02595485]
  [-0.03420796 -0.03776937 -0.01532779  0.02567506 -0.04505258
   -0.04434186  0.02496746 -0.03646117 -0.03092648  0.02595485]
  [-0.03420796 -0.03776937 -0.01532779  0.02567506 -0.04505258
   -0.04434186  0.02496746 -0.03646117 -0.03092648  0.02595485]
  [-0.0162627  -0.00686593  0.0207576  -0.03949002 -0.04378505
    0.00830678  0.04668463  0.02091653  0.03579111  0.00138693]
  [ 0.04168551  0.03062064  0.01592472 -0.00214869 -0.04990872
   -0.0081948   0.04247181  0.01584608  0.02644379 -0.03842119]
  [-0.03838784 -0.02170075  0.01314293 -0.03981489 -0.00875556
   -0.03406781 -0.04632014 -0.03810064  0.00172836 -0.01538662]
  [-0.01399852  0.04925833 -0.0334331  -0.04170553 -0.04977

In [26]:
embedded_docs[0]

array([  0,   0,   0,   0, 209, 301, 315, 116])

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]

In [27]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [28]:
vocubulary_size = 800

In [29]:
onehot = [one_hot(words,vocubulary_size)for words in sent]
print(onehot)

[[422, 176, 642, 396, 695, 521], [540, 305, 642, 87, 91, 513], [766, 734, 418, 108], [422, 724, 642, 521, 422, 228], [666, 753, 454, 642, 87, 91, 513], [120, 642, 87, 91, 30, 429]]


In [30]:
## pre padding
sentence_length=15
embedded_document = pad_sequences(onehot,padding='pre',maxlen=sentence_length)
print(embedded_document)

[[  0   0   0   0   0   0   0   0   0 422 176 642 396 695 521]
 [  0   0   0   0   0   0   0   0   0 540 305 642  87  91 513]
 [  0   0   0   0   0   0   0   0   0   0   0 766 734 418 108]
 [  0   0   0   0   0   0   0   0   0 422 724 642 521 422 228]
 [  0   0   0   0   0   0   0   0 666 753 454 642  87  91 513]
 [  0   0   0   0   0   0   0   0   0 120 642  87  91  30 429]]


In [31]:
dimension = 5

In [32]:
model=Sequential()
model.add(Embedding(vocubulary_size,dimension,input_length=sentence_length))
model.compile('adam','mse') # adam optimizer and mean square error 

In [33]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 15, 5)             4000      
                                                                 
Total params: 4000 (15.62 KB)
Trainable params: 4000 (15.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [34]:
model.predict(embedded_document[0])

1/1 [==============================] - 0s 50ms/step


array([[ 0.03140048,  0.03419082,  0.04378289,  0.03652248,  0.02969876],
       [ 0.03140048,  0.03419082,  0.04378289,  0.03652248,  0.02969876],
       [ 0.03140048,  0.03419082,  0.04378289,  0.03652248,  0.02969876],
       [ 0.03140048,  0.03419082,  0.04378289,  0.03652248,  0.02969876],
       [ 0.03140048,  0.03419082,  0.04378289,  0.03652248,  0.02969876],
       [ 0.03140048,  0.03419082,  0.04378289,  0.03652248,  0.02969876],
       [ 0.03140048,  0.03419082,  0.04378289,  0.03652248,  0.02969876],
       [ 0.03140048,  0.03419082,  0.04378289,  0.03652248,  0.02969876],
       [ 0.03140048,  0.03419082,  0.04378289,  0.03652248,  0.02969876],
       [-0.00753939,  0.02700101, -0.04211671,  0.04088893, -0.00963812],
       [-0.02463684, -0.02309457, -0.04429134, -0.0495985 ,  0.03326447],
       [-0.04505031, -0.04739777, -0.03099238,  0.01759274, -0.01643722],
       [-0.02399907, -0.04204958,  0.04484123, -0.02894044,  0.04331135],
       [-0.01776807,  0.04782078,  0.0